name: "Coverage"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ github.actor == 'dependabot[bot]' && secrets.REPO_AND_READ_PACKAGES_PAT || secrets.XML_SUBMODULE_PAT }}
          # XML_SUBMODULE_PAT is a secret token on repository level with repo scope; expires in Jan2026
          # https://github.com/Hochfrequenz/xml-fundamend-python/settings/secrets/actions/XML_AHB_MIG_Token
          # REPO_AND_READ_PACKAGES_PAT is a secret token on organization level
          # https://github.com/organizations/Hochfrequenz/settings/secrets/dependabot/REPO_AND_READ_PACKAGES_PAT
          submodules: "recursive"
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: uv sync --group coverage --extra sqlmodels --extra ahbicht --extra cli
      - name: Run Tests and Record Coverage
        run: |
          cd unittests
          uv run coverage run -m pytest -vv
          uv run coverage html --omit .venv/*,unittests/*
          uv run coverage report --fail-under 94 --omit .venv/*,unittests/*
